Logic synth rs5
gaph-pucrs/RS5 pull request #26
Opened 2024-08-12 18:04 UTC by dubernardon

2024-08-12 18:54 UTC, aedalzotto requested changes
Please see my comments.
Also add a proper description to this PR.

2024-08-12 18:54 UTC, aedalzotto commented on rtl/CSRBank.sv
> +=======
* Fix this conflict
* Do not change default parameters (e.g. XOSVMEnable should be 1'b0)
* Change `ifdef DEBUG` for `ifndef SYNTH`

2024-08-12 18:54 UTC, aedalzotto commented on rtl/CSRBank.sv
> +>>>>>>> origin/master
Unsolved conflict here too

2024-08-12 18:54 UTC, aedalzotto commented on rtl/CSRBank.sv
> +            interrupt_pending_o <= 0;
Please tell us in this PR why this change was made.
Commit messages are not clear

2024-08-12 18:54 UTC, aedalzotto commented on rtl/CSRBank.sv
> +        `ifdef DEBUG
Change `ifdef DEBUG` for `ifndef SYNTH`

2024-08-12 18:54 UTC, aedalzotto commented on rtl/RS5.sv
> +    parameter rv32_e        RV32           = RV32M,
Please do not change default parameters. Revert to RV32I.

2024-08-12 18:54 UTC, aedalzotto commented on rtl/RS5.sv
> +    `ifdef DEBUG
Change `ifdef DEBUG` for `ifndef SYNTH`

2024-08-12 18:54 UTC, aedalzotto commented on rtl/RS5.sv
> +            `ifdef DEBUG
Change `ifdef DEBUG` for `ifndef SYNTH`

2024-08-12 18:54 UTC, aedalzotto commented on rtl/RS5.sv
> +      `ifdef DEBUG
Change `ifdef DEBUG` for `ifndef SYNTH`

2024-08-12 18:54 UTC, aedalzotto commented on rtl/align.sv
> +            enable_r <= enable_i;
Is this change correct?
The commit message is not clear why this change was made.
Please tell us.

2024-08-12 18:54 UTC, aedalzotto commented on rtl/align.sv
> +        else if (enable_i && !hazard_i && enable_r) begin
Is this change correct?
The commit message is not clear why this change was made.
Please tell us.

2024-08-12 18:54 UTC, aedalzotto commented on rtl/decode.sv
> +    parameter bit           COMPRESSED  = 1'b1
Please keep default parameters (COMPRESSED = 1'b0)

2024-08-12 18:54 UTC, aedalzotto commented on rtl/execute.sv
> +    parameter rv32_e        RV32        = RV32M,
Please keep default parameters (RV32 = RV32I)

2024-08-12 18:54 UTC, aedalzotto commented on rtl/execute.sv
> +        if ((killed) == 1'b0) begin
Why was this change made?
Not clear by commit messages.
Please tell us.

2024-08-12 18:54 UTC, aedalzotto commented on rtl/fetch.sv
> +    parameter bit COMPRESSED    = 1'b1
Please keep default parameters (COMPRESSED = 1'b0)

2024-08-12 18:54 UTC, aedalzotto commented on rtl/regbank.sv
> +    `ifdef DEBUG
Please change to `ifndef SYNTH`

2024-08-12 18:54 UTC, aedalzotto commented on rtl/regbank.sv
> +    `ifdef DEBUG
Please change to `ifndef SYNTH`

2024-08-12 18:54 UTC, aedalzotto commented on sim/testbench.sv
> +    `ifdef DEBUG
Please change to `ifndef SYNTH`

2024-08-12 18:54 UTC, aedalzotto commented on sim/testbench.sv
> +        `ifdef DEBUG
Please change to `ifndef SYNTH`

2024-08-12 18:54 UTC, aedalzotto commented on sim/testbench.sv
> +        `ifdef DEBUG
Please change to `ifndef SYNTH`

2024-08-13 13:14 UTC, aedalzotto commented
I have solved conflicts and changed the debugging definitions to always enabled when SYNTH is not defined.
Please explain the remaining questions and add a description to this PR.

2024-08-13 14:52 UTC, aedalzotto commented
Tested and good to go after the PR is documented

2024-08-13 17:29 UTC, dubernardon commented on rtl/execute.sv
> +        if ((killed) == 1'b0) begin
Optimization

2024-08-13 17:32 UTC, dubernardon commented on rtl/align.sv
> +        else if (enable_i && !hazard_i && enable_r) begin
To works with physical memory

2024-08-13 17:33 UTC, dubernardon commented on rtl/align.sv
> +            enable_r <= enable_i;
To work with physical memory

2024-08-13 17:56 UTC, aedalzotto approved these changes

2024-08-13 17:57 UTC, merged